tickers_scale: 20

yahoo:
  interval: "1d"
  period: "2y"

db:
  org: "local"
  name: "db0"
  bucket: "stocks_prices"
  url: "http://localhost:8086"
  token: "RDV6dIFHQzEKx1Hb5m30xZ0trij_4nqjTg8SjDPHYw3ZWzkQmG0Tr55GObX2m3mA_K7Qg2-CUsx0j3hot_9HgQ=="
  stock_tickers_table: "tickers"
  stock_prices_table: "stock_price"

POSTGRES_USER: postgres
POSTGRES_PASSWORD: password
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: postgres