version: '2'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/temp/influxdb
    environment:
      - INFLUXDB_DB="db0"
      - DOCKER_INFLUXDB_INIT_USERNAME="admin"
      - DOCKER_INFLUXDB_INIT_PASSWORD="12345678"
      - DOCKER_INFLUXDB_INIT_ORG="local"
      - DOCKER_INFLUXDB_INIT_BUCKET="stock_prices"



volumes:
  influxdb-storage:
