[tool.poetry]
name = "data_downloader"
version = "0.1.0"
description = "stocks data downloader"
authors = ["Adam Yodinsky"]

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.1.64"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
